volumes:
  db_data:
    name: 'db_data' 

services:
  web:
    build: .
    env_file:
      - .env
    environment:
      - DOCKERIZED=1
    ports:
      - "8000:8000"
    volumes: 
      - db_data:/app/data
    